import { inter } from "@/lib/fonts/fonts";
import "./globals.css";

import RefreshingProvider from "@/components/custom/provider/RefreshingProvider";
import { Toaster } from "sonner";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} text-[16px] text-neutral-600 antialiased`}
            >
                <RefreshingProvider>
                    <Toaster />
                    {children}
                </RefreshingProvider>
            </body>
        </html>
    );
}